name = "MSMP"
author = "Eloir Corona"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "687a97342be42eef145890e45278be6a2a29acc06ae4be9cd82b9f502b8befd1"

[versions]
minecraft = "26.2"
neoforge = "26.2.0.32-beta"
