name = "MSMP"
author = "Eloir Corona"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d62d4c105b197e2a54a55f41bb9add279edebceb066e1e3171cbd3c99055918c"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.244"
