name = "MSMP"
author = "Eloir Corona"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1d4067461e15f8fca0bf930843aaa61d26cd30f6ae383159db6de67dbb396ad8"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.244"
